version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-docker
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: calculator
      DB_USERNAME: vlastit
      DB_PASSWORD: 7773410rR
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: calculator
      MYSQL_USER: vlastit
      MYSQL_PASSWORD: 7773410rR
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379